{
 "title": "Hyperliquid Validator",
 "tags": [
  "hyperliquit",
  "testnet",
  "validators"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "validator_name",
    "label": "Validator Name",
    "query": {
     "query": "label_values(hyperliquid_validator_predicted_apr,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n  <img src=\"https://pbs.twimg.com/profile_images/1646991609416806408/vKLEZxhh_400x400.png\" alt=\"Hyperliquid Exporter Logo\" style=\"width: 100px; height: 100px; border-radius: 50%; margin-right: 20px;\"/>\n  <div>\n    <h1>Hyperliquid Testnet Dashboard</h1>\n    <p>This dashboard is free and open-source, available at <a href=\"https://github.com/l0ix/hyperliquid-testnet-performance-exporter\" target=\"_blank\">GitHub</a>.</p>\n  </div>\n</div>\n"
   }
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  { "title": "Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Daily",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hyperliquid_validator_uptime_fraction{name=~\"$validator_name\",period=\"day\"} * 100",
     "legendFormat": "{{validator_name}}"
    }
   ]
  },
  {
   "title": "Weekly",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hyperliquid_validator_uptime_fraction{name=~\"$validator_name\",period=\"week\"} * 100",
     "legendFormat": "{{validator_name}}"
    }
   ]
  },
  {
   "title": "Monthly",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hyperliquid_validator_uptime_fraction{name=~\"$validator_name\",period=\"month\"} * 100",
     "legendFormat": "{{validator_name}}"
    }
   ]
  },
  { "title": "Other stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Stake",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hyperliquid_validator_stake{name=~\"$validator_name\"} / 100000000",
     "legendFormat": "{{validator_name}}"
    }
   ]
  },
  {
   "title": "Comission",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hyperliquid_validator_commission{name=~\"$validator_name\"} *100",
     "legendFormat": "{{validator_name}}"
    }
   ]
  },
  {
   "title": "In active set over time",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hyperliquid_validator_status{name=~\"$validator_name\"}",
     "legendFormat": "{{validator_name}}"
    }
   ]
  },
  {
   "title": "Is jailed over time",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(hyperliquid_validator_status{name=~\"$validator_name\", is_jailed=\"true\"} * 1) OR \n(hyperliquid_validator_status{name=~\"$validator_name\", is_jailed=\"false\"} * 1)",
     "legendFormat": "{{validator_name}}"
    }
   ]
  }
 ]
}